remote_theme: just-the-docs/just-the-docs

title: XR Studio Guides
description: A collection of guides for operating the LSU XR Studio for virtual production.

markdown: GFM

plugins:
  - jemoji

# Aux links for the upper right navigation

aux_links:
  "XR Studio Guides on GitHub":
    - "//github.com/lsuxrstudio/xrstudioguides"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/lsuxrstudio/xrstudioguides" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately