remote_theme: just-the-docs/just-the-docs

title: XR Studio Guides
description: A collection of guides for operating the LSU XR Studio for virtual production.

markdown: GFM

plugins:
  - jemoji

# Aux links for the upper right navigation

aux_links:
  "XR Studio Guides on GitHub":
    - "//lsuxrstudio.github.io/XRStudioSetup"